import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/screens/LoginScreen.tsx', import.meta.url), 'utf8');
const authContext = await readFile(new URL('../src/state/AuthContext.tsx', import.meta.url), 'utf8');

assert.match(source, /const \[passwordConfirmation, setPasswordConfirmation\] = useState\(''\)/, '確認用パスワードを独立して保持する');
assert.match(source, /mode === 'register' && password !== passwordConfirmation/, '新規登録時だけ一致確認を行う');
assert.match(source, /確認用パスワードが一致しません/, '不一致理由を利用者へ明示する');
assert.match(source, /id="auth-password-confirmation"/, '確認用入力欄を新規登録画面へ表示する');
assert.match(source, /autoComplete="new-password"/, 'パスワードマネージャーへ新規パスワード入力として伝える');
assert.match(source, /if \(busy\) return;[\s\S]*setMode\(next\)/, '認証処理中はモードを切り替えない');
assert.match(source, /className="auth-card" aria-busy=\{busy\}/, '認証領域の処理中状態を支援技術へ伝える');
assert.match(source, /id="auth-username"[\s\S]*disabled=\{busy\}/, '認証処理中はユーザー名を変更できない');
assert.match(source, /id="auth-password"[\s\S]*disabled=\{busy\}/, '認証処理中はパスワードを変更できない');
assert.match(source, /id="auth-password-confirmation"[\s\S]*disabled=\{busy\}/, '認証処理中は確認用パスワードを変更できない');
assert.match(source, /className="password-toggle-btn"[\s\S]*disabled=\{busy\}/, '認証処理中はパスワード表示状態を変更できない');
assert.match(source, /setPassword\(''\)[\s\S]*setPasswordConfirmation\(''\)[\s\S]*setShowPassword\(false\)/, 'モード切り替え時に認証情報と表示状態を破棄する');
assert.match(source, /const clearDisplayedError = \(\) => \{[\s\S]*setLocalError\(null\)[\s\S]*clearError\(\)/, '入力を直し始めたらローカル・API双方の古いエラーを消す');
assert.match(source, /id="auth-username"[\s\S]*onChange=\{\(e\) => \{[\s\S]*setUsername\(e\.target\.value\)[\s\S]*clearDisplayedError\(\)/, 'ユーザー名の修正時に古いエラーを消す');
assert.match(source, /id="auth-password"[\s\S]*onChange=\{\(e\) => \{[\s\S]*setPassword\(e\.target\.value\)[\s\S]*clearDisplayedError\(\)/, 'パスワードの修正時に古いエラーを消す');
assert.match(source, /id="auth-password-confirmation"[\s\S]*onChange=\{\(e\) => \{[\s\S]*setPasswordConfirmation\(e\.target\.value\)[\s\S]*clearDisplayedError\(\)/, '確認用パスワードの修正時に古いエラーを消す');
assert.match(authContext, /function nonEmptyString\(value: unknown\): string \| null \{[\s\S]*value\.trim\(\)[\s\S]*return normalized \? normalized : null/, '保存済み認証識別子は空白だけの値を受け入れない');
assert.match(authContext, /const id = nonEmptyString\(stored\.id\)[\s\S]*const username = nonEmptyString\(stored\.username\)[\s\S]*if \(id && username/, 'v2認証ヒントは非空のIDとユーザー名が揃う場合だけ復元する');
assert.match(authContext, /stored\.memoryOwner === undefined \? null : nonEmptyString\(stored\.memoryOwner\)[\s\S]*stored\.memoryOwner === undefined \|\| memoryOwner/, '壊れたmemoryOwnerを持つ認証ヒントを拒否する');
assert.match(authContext, /const legacyUsername = nonEmptyString\(localStorage\.getItem\(AUTH_HINT_KEY\)\)/, '旧形式の空ユーザー名も認証済みとして復元しない');
assert.match(authContext, /function clearHints\(\): void \{[\s\S]*removeItem\(AUTH_HINT_KEY\)[\s\S]*removeItem\(AUTH_USER_HINT_KEY\)/, '認証ヒントを一括破棄できる');
assert.match(authContext, /if \(user\.id\) \{[\s\S]*setItem\(AUTH_USER_HINT_KEY, JSON\.stringify\(user\)\)[\s\S]*\} else \{[\s\S]*removeItem\(AUTH_USER_HINT_KEY\)[\s\S]*setItem\(AUTH_HINT_KEY, user\.username\)/, '旧形式ユーザーへ切り替える時は古いv2ヒントを残さない');
assert.match(authContext, /catch \{[\s\S]*try \{[\s\S]*clearHints\(\)[\s\S]*\} catch/, 'ヒント保存が途中失敗した場合は混在した認証情報を破棄する');
assert.match(authContext, /const operationInFlight = useRef\(false\)/, '再描画前でも認証操作を排他できる同期ロックを持つ');
assert.match(authContext, /if \(operationInFlight\.current\) return false;[\s\S]*operationInFlight\.current = true/, '同時に開始された二つ目の認証操作を拒否する');
assert.match(authContext, /const authStateVersion = useRef\(0\)/, '認証状態を変更する操作の世代を追跡する');
assert.match(authContext, /operationInFlight\.current = true;[\s\S]*authStateVersion\.current \+= 1/, '認証操作開始時に進行中の再確認結果を無効化する');
assert.match(authContext, /const reconciliationInFlight = useRef<Promise<void> \| null>\(null\)/, '進行中のセッション再確認を一つのPromiseとして追跡する');
assert.match(authContext, /const reconcile = useCallback[\s\S]*if \(existing\) return existing;[\s\S]*if \(!isCurrent\(\)\) return;[\s\S]*const nextUser = await migratedUser/, '重複再確認を統合し、古い応答では所有者移行を開始しない');
assert.match(authContext, /const waitForReconciliation = useCallback[\s\S]*if \(pending\) await pending/, '認証操作は進行中の所有者移行完了を待つ');
assert.match(authContext, /catch \(e\) \{[\s\S]*if \(!isCurrent\(\)\) return;[\s\S]*const err = e as ApiError/, '古い再確認エラーでもログアウト後の状態を上書きしない');
assert.match(authContext, /if \(err\.isNetworkError\)[\s\S]*if \(hint\)[\s\S]*setOfflineUnverified\(true\)[\s\S]*else \{[\s\S]*setUser\(null\)[\s\S]*setStatus\('anonymous'\)[\s\S]*setOfflineUnverified\(false\)/, 'オフラインヒントがない通信失敗では古い認証状態を完全に破棄する');
assert.match(authContext, /setUser\(null\)[\s\S]*setStatus\('anonymous'\)[\s\S]*setOfflineUnverified\(false\)[\s\S]*writeHint\(null\)/, 'セッション無効時は利用者・状態・未確認フラグ・保存ヒントを一貫して破棄する');
assert.match(authContext, /const login = useCallback[\s\S]*if \(!beginOperation\(\)\) return false;[\s\S]*await waitForReconciliation\(\);[\s\S]*apiLogin/, 'ログインは再確認と所有者移行が終わってから送信する');
assert.match(authContext, /const register = useCallback[\s\S]*if \(!beginOperation\(\)\) return false;[\s\S]*await waitForReconciliation\(\);[\s\S]*apiRegister/, '登録は再確認と所有者移行が終わってから送信する');
assert.match(authContext, /const logout = useCallback[\s\S]*if \(!beginOperation\(\)\) return;[\s\S]*await waitForReconciliation\(\);[\s\S]*apiLogout/, 'ログアウトも再確認と所有者移行の完了後に実行する');

console.log('✅ auth registration confirmation regressions passed');
