import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';

const read = async (path) => await readFile(new URL(`../${path}`, import.meta.url), 'utf8');

const feature = await read('src/features/memory/ui/MemoryFeature.tsx');
const home = await read('src/features/memory/ui/MemoryHome.tsx');
const setup = await read('src/features/memory/ui/MemoryStudySetup.tsx');
const editor = await read('src/features/memory/ui/MemoryEditor.tsx');
const study = await read('src/features/memory/ui/MemoryStudy.tsx');
const result = await read('src/features/memory/ui/MemoryResult.tsx');
const simpleSession = await read('src/features/memory/application/simpleSession.ts');
const cardUx = await read('src/styles/memory-card-ux.css');
const compactFixes = await read('src/styles/memory-compact-fixes.css');
const main = await read('src/main.tsx');

assert.doesNotMatch(feature, /MemoryAnalytics/u, '分析画面をfeatureから外す');
await assert.rejects(access(new URL('../src/features/memory/ui/MemoryAnalytics.tsx', import.meta.url)), '分析画面ファイルを削除する');
assert.match(home, /10問始める/u, 'ホームの主操作は10問開始');
assert.match(home, /createSimpleStudySession/u, 'ホームはカード専用セッションを使う');
assert.match(home, /summaries\.length > 0[\s\S]*カード追加[\s\S]*セット追加/u, 'セット未作成時はカード追加ではなくセット追加を案内する');
assert.doesNotMatch(home, /setId: summaries\[0\]\?\.set\.id/u, '存在しないセットへカードを追加する導線を残さない');
assert.doesNotMatch(home, /Input／Output差|Composition/u, 'ホームへ専門的な分析を出さない');
assert.match(setup, /日本語 → 英語/u);
assert.match(setup, /英語 → 日本語/u);
assert.doesNotMatch(setup, /文中で使う|ミックス|AI未確認|回答方式/u, '学習設定から不要な選択肢を削除する');
assert.doesNotMatch(editor, /問題形式・指定表現|EXERCISE_TYPES|MemoryExerciseDraft/u, 'カード編集から問題作成機能を削除する');
assert.match(editor, /別の英語を追加/u, '自然な別解登録は残す');
assert.doesNotMatch(study, /gradeAnswer|multiple_choice|guided_composition|free_composition|ERROR_LABELS|ミス分類/u, '学習画面から自動問題・細分類を削除する');
assert.match(study, /まだ/u);
assert.match(study, /あやしい/u);
assert.match(study, /覚えた/u);
assert.match(study, /\[session\?\.answerCount, target\?\.id\]/u, '同じカードの即時再出題でも表面へ戻す');
assert.match(study, /aria-label="答えを見る"/u, 'カード表面をタップして答えを表示できる');
assert.match(study, /aria-label="問題に戻る"/u, '答え表示後もカード表面へ戻せる');
assert.match(study, /SWIPE_THRESHOLD_PX/u, '左右スワイプでカードをめくれる');
assert.match(cardUx, /perspective:\s*1500px/u, '3Dカード空間を定義する');
assert.match(cardUx, /transform-style:\s*preserve-3d/u, '表裏を3Dで保持する');
assert.match(cardUx, /rotateY\(180deg\)/u, '反転アニメーションを定義する');
assert.match(cardUx, /backface-visibility:\s*hidden/u, '反転中に裏写りさせない');
assert.match(cardUx, /\.memory-simple-set-cards > \.card \+ \.card[\s\S]*margin-top:\s*0/u, '2枚目だけ下へずれるグローバルmarginを解除する');
assert.match(cardUx, /\.memory-simple-set-card[\s\S]*height:\s*100%/u, 'セットカードの高さを揃える');
assert.match(cardUx, /prefers-reduced-motion:\s*reduce/u, '視差低減設定では安全な切替へ落とす');
assert.match(compactFixes, /\.memory-card-swipe-hint[\s\S]*display:\s*none/u, '説明的なスワイプ文言を画面へ出さない');
assert.match(compactFixes, /\.memory-simple-result-grid > \.card \+ \.card[\s\S]*margin-top:\s*0/u, '結果カードが2枚目以降だけ大きくならない');
assert.match(compactFixes, /\.memory-simple-result-grid > \.card[\s\S]*min-height:\s*104px/u, '結果カードを簡潔な固定高さへ揃える');
assert.match(main, /memory-card-ux\.css[\s\S]*memory-compact-fixes\.css/u, '暗記カードUX修正を最後に読み込む');
assert.doesNotMatch(result, /苦手分析|Learning Target|Composition/u, '結果画面から分析導線と専門用語を削除する');
assert.match(simpleSession, /!target\.exerciseId/u, '旧問題データを出題対象から除外する');
assert.match(simpleSession, /includeUnverifiedAi: false/u, '未確認AIデータを通常学習へ混ぜない');

console.log('🎉 ALL PASS (memory simple UX contract)');