import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';

const read = async (path) => await readFile(new URL(`../${path}`, import.meta.url), 'utf8');

const feature = await read('src/features/memory/ui/MemoryFeature.tsx');
const home = await read('src/features/memory/ui/MemoryHome.tsx');
const setup = await read('src/features/memory/ui/MemoryStudySetup.tsx');
const editor = await read('src/features/memory/ui/MemoryEditor.tsx');
const study = await read('src/features/memory/ui/MemoryStudy.tsx');
const result = await read('src/features/memory/ui/MemoryResult.tsx');
const simpleSession = await read('src/features/memory/application/simpleSession.ts');
const cardUx = await read('src/styles/memory-card-ux.css');
const androidFlipFix = await read('src/styles/memory-android-flip-fix.css');
const compactFixes = await read('src/styles/memory-compact-fixes.css');
const studyPolish = await read('src/styles/memory-study-polish.css');
const main = await read('src/main.tsx');

assert.doesNotMatch(feature, /MemoryAnalytics/u, '分析画面をfeatureから外す');
await assert.rejects(access(new URL('../src/features/memory/ui/MemoryAnalytics.tsx', import.meta.url)), '分析画面ファイルを削除する');
assert.match(home, /10問始める/u, 'ホームの主操作は10問開始');
assert.match(home, /createSimpleStudySession/u, 'ホームはカード専用セッションを使う');
assert.match(home, /eligible: targets\.length/u, 'ホームの即時学習可否は実際の出題対象件数で判定する');
assert.match(home, /summary\.eligible === 0[\s\S]*出題できるカードなし/u, '未確認AIカードだけのセットでは開始操作を無効化して理由を表示する');
assert.doesNotMatch(home, /summary\.cards === 0/u, '生カード件数だけで即時学習を有効化しない');
assert.match(home, /summaries\.length === 1[\s\S]*カード追加[\s\S]*セット追加/u, '追加先が一意な場合だけカード追加へ直接進み、それ以外はセット追加を案内する');
assert.doesNotMatch(home, /setId: summaries\[0\]\?\.set\.id/u, '存在しないセットへカードを追加する導線を残さない');
assert.match(home, /filtered\.length === 0[\s\S]*一致する暗記セットがありません[\s\S]*検索を解除/u, '検索0件時は理由と解除導線を表示する');
assert.match(home, /role="status"/u, '検索結果0件を支援技術へ通知する');
assert.equal(home.match(/requestSync\(true\)\.catch\(\(\) => undefined\)/gu)?.length, 3, 'セット作成後・学習開始後・手動同期の失敗を未処理Promiseにしない');
assert.doesNotMatch(home, /void requestSync\(true\)(?!\.catch)/u, '暗記ホームから同期を未処理のまま開始しない');
assert.match(home, /disabled=\{isStarting \|\| syncStatus === 'syncing'\}[\s\S]*aria-busy=\{syncStatus === 'syncing'\}[\s\S]*aria-label=\{syncStatus === 'syncing' \? '暗記データを同期中' : '暗記データを同期'\}/u, '学習開始中または手動同期中は再操作を止めてボタン自体へ処理中状態を通知する');
assert.match(home, /<RefreshCw size=\{15\} aria-hidden="true" \/>/u, '同期アイコンを読み上げ名へ重複させない');
assert.match(home, /await createMemorySet[\s\S]*try \{[\s\S]*await refresh\(\);[\s\S]*\} catch \(caught\) \{[\s\S]*console\.error[\s\S]*\}[\s\S]*requestSync\(true\)[\s\S]*onClose\(\)/u, 'セット保存後の一覧更新失敗でも作成成功として同期と画面更新を続ける');
assert.doesNotMatch(home, /await createMemorySet[^;]*;\s*await refresh\(\);\s*void requestSync/u, '一覧更新をセット作成全体の成功条件へ戻さない');
assert.match(home, /const \{ repository, ready, error, sets,[\s\S]*\} = useMemory\(\)/u, 'Contextのセット更新を暗記ホームの再読込トリガーとして受け取る');
assert.match(home, /\[pendingCount, ready, repository, sets, snapshotReloadKey\]/u, '同期後にセット一覧が更新されたらカード件数と苦手集計を再読込する');
assert.doesNotMatch(home, /Input／Output差|Composition/u, 'ホームへ専門的な分析を出さない');
assert.match(setup, /日本語 → 英語/u);
assert.match(setup, /英語 → 日本語/u);
assert.match(setup, /const \{ repository, ready, sets, activeSession, navigate, refresh, requestSync \} = useMemory\(\)/u, '暗記データ準備完了後にセット選択と途中セッションを検証し、開始後の同期手段も取得する');
assert.match(setup, /if \(!ready\) return;[\s\S]*availableSetIds[\s\S]*current\.filter\(\(setId\) => availableSetIds\.has\(setId\)\)/u, '削除済みセットIDを学習設定から除外する');
assert.match(setup, /eligibilityRetry[\s\S]*repository\.loadSetBundle[\s\S]*\[direction, eligibilityKey, eligibilityRetry, repository, selectedSetIds\]/u, 'カード件数の再読み込みで同じセットを再取得する');
assert.match(setup, /カード件数を読み込めませんでした。[\s\S]*setEligibilityRetry\(\(current\) => current \+ 1\)[\s\S]*再読み込み/u, 'カード件数の読込失敗から直接再試行できる');
assert.doesNotMatch(setup, /セットを選び直してください/u, '再試行のためにセット選択のやり直しを強制しない');
assert.match(setup, /handleRadioKeyDown[\s\S]*ArrowLeft[\s\S]*ArrowRight[\s\S]*ArrowUp[\s\S]*ArrowDown[\s\S]*Home[\s\S]*End/u, 'ラジオ選択を矢印・Home・Endキーで操作できる');
assert.match(setup, /tabIndex=\{direction === 'output' \? 0 : -1\}[\s\S]*tabIndex=\{direction === 'input' \? 0 : -1\}/u, '出題方向は選択中の項目だけをTab移動対象にする');
assert.match(setup, /tabIndex=\{countChoice === value \? 0 : -1\}/u, '問題数は選択中の項目だけをTab移動対象にする');
assert.match(setup, /requestAnimationFrame[\s\S]*data-radio-value/u, 'キー操作後に新しい選択項目へフォーカスを移す');
assert.match(setup, /const startInFlight = useRef\(false\)[\s\S]*if \(!repository \|\| startInFlight\.current[\s\S]*startInFlight\.current = true[\s\S]*finally \{[\s\S]*startInFlight\.current = false/u, '学習開始を同期ロックでsingle-flight化する');
assert.match(setup, /<section className="memory-study-setup memory-simple-setup" aria-busy=\{starting\}>/u, '学習開始中であることを設定画面全体へ通知する');
assert.match(setup, /aria-label="暗記ホームへ戻る" disabled=\{starting\}/u, '学習開始中は戻る操作を止める');
assert.equal(setup.match(/<fieldset disabled=\{starting\}>/gu)?.length, 3, '学習開始中はセット・出題方向・問題数を変更できない');
assert.match(setup, /disabled=\{starting\}[\s\S]*setEligibilityRetry/u, '学習開始中はカード件数の再読み込みを止める');
assert.match(setup, /aria-busy=\{starting\}[\s\S]*準備中…/u, '開始ボタン自体にも処理中状態を通知する');
assert.match(setup, /const created = await createSimpleStudySession[\s\S]*try \{[\s\S]*await refresh\(\);[\s\S]*\} catch \(caught\) \{[\s\S]*console\.error[\s\S]*\}[\s\S]*requestSync\(true\)[\s\S]*navigate\(\{ name: 'study', sessionId: created\.session\.id \}\)/u, 'セッション作成後の一覧更新失敗でも同期と学習画面への遷移を止めない');
assert.doesNotMatch(setup, /const created = await createSimpleStudySession[^;]*;\s*await refresh\(\);\s*navigate\(\{ name: 'study'/u, '一覧更新をセッション作成全体の成功条件へ戻さない');
assert.doesNotMatch(setup, /文中で使う|ミックス|AI未確認|回答方式/u, '学習設定から不要な選択肢を削除する');
assert.doesNotMatch(editor, /問題形式・指定表現|EXERCISE_TYPES|MemoryExerciseDraft/u, 'カード編集から問題作成機能を削除する');
assert.match(editor, /別の英語を追加/u, '自然な別解登録は残す');
assert.doesNotMatch(study, /gradeAnswer|multiple_choice|guided_composition|free_composition|ERROR_LABELS|ミス分類/u, '学習画面から自動問題・細分類を削除する');
assert.match(study, /まだ/u);
assert.match(study, /あやしい/u);
assert.match(study, /覚えた/u);
assert.match(study, /\[session\?\.answerCount, target\?\.id\]/u, '同じカードの即時再出題でも表面へ戻す');
assert.match(study, /aria-label="答えを見る"/u, 'カード表面をタップして答えを表示できる');
assert.match(study, /aria-label="問題に戻る"/u, '答え表示後もカード表面へ戻せる');
assert.match(study, /className="memory-study-flip-shell"[\s\S]*onPointerDown[\s\S]*onPointerUp/u, '固定シェルで左右スワイプを受ける');
assert.equal(study.match(/onClick=\{\(\) => handleFaceClick\(/gu)?.length, 2, '表面と裏面がそれぞれ明示的な反転操作を持つ');
assert.match(study, /SWIPE_THRESHOLD_PX/u, '左右スワイプでカードをめくれる');
assert.match(study, /setFlipDirection\(next \? 'to-answer' : 'to-question'\)/u, 'タップとスワイプの方向を明示的な反転状態へ変換する');
assert.match(study, /flip-\$\{flipDirection\}/u, 'Android向けの反転方向クラスをカードへ付与する');
assert.match(study, /animationName\.startsWith\('memory-card-android-flip-'\)/u, '反転完了後に一時クラスを解除する');
assert.match(study, /undoMemoryAnswer[\s\S]*requestSyncSafely\(false\)/u, '回答取り消しも安全な端末間同期を要求する');
assert.match(study, /catch \(caught\)[\s\S]*回答の取り消しを保存できませんでした/u, '回答取り消しの保存失敗を利用者へ通知する');
assert.doesNotMatch(study, /<main className="memory-study-stage">/u, 'アプリ全体のmain内へ学習画面のmainランドマークを重ねない');
assert.match(study, /<div className="memory-study-stage">/u, '学習画面の視覚レイアウトはランドマークを増やさず維持する');
assert.match(study, /data-card-side=\{revealed \? 'answer' : 'question'\}/u, '問題面と答え面をCSSから安全に識別できる');
assert.match(cardUx, /perspective:\s*1500px/u, '3Dカード空間を定義する');
assert.match(cardUx, /transform-style:\s*preserve-3d/u, '表裏を3Dで保持する');
assert.match(cardUx, /rotateY\(180deg\)/u, '反転アニメーションを定義する');
assert.match(cardUx, /backface-visibility:\s*hidden/u, '反転中に裏写りさせない');
assert.match(studyPolish, /:has\(\.memory-study-card\[data-card-side='question'\]\) \.memory-study-stage \{[\s\S]*overflow:\s*hidden[\s\S]*overscroll-behavior:\s*none/u, '問題面では学習ステージを縦スクロールさせない');
assert.match(studyPolish, /:has\(\.memory-study-card\[data-card-side='question'\]\) \.memory-study-flip-shell \{[\s\S]*touch-action:\s*none/u, '問題面のカード操作でブラウザのパンを開始しない');
assert.match(studyPolish, /:has\(\.memory-study-card\[data-card-side='question'\]\) \.memory-study-card-front \{[\s\S]*overflow:\s*hidden/u, '問題カード自身にもスクロールを作らない');
assert.match(studyPolish, /:has\(\.memory-study-card\[data-card-side='answer'\]\) \.memory-study-stage \{[\s\S]*overflow-y:\s*auto/u, '答え面では長い内容を縦スクロールできる');
assert.match(studyPolish, /\.memory-again \{\s*--assessment-tone:\s*#a65f6f/u, 'まだは彩度を抑えたローズ色にする');
assert.match(studyPolish, /\.memory-partial \{\s*--assessment-tone:\s*#b47b36/u, 'あやしいは彩度を抑えたアンバー色にする');
assert.doesNotMatch(studyPolish, /color:\s*#fff[\s\S]*memory-again|color:\s*#fff[\s\S]*memory-partial/u, 'まだ・あやしいを白文字の強い全面色へ戻さない');
assert.match(androidFlipFix, /\.memory-simple-study \.memory-study-card\.revealed[\s\S]*animation:\s*memory-card-in/u, '反転時も親カードの合成レイヤーを維持する');
assert.match(androidFlipFix, /-webkit-perspective:\s*1500px/u, 'Android Chromium向けにWebKit perspectiveを明示する');
assert.match(androidFlipFix, /-webkit-transform-style:\s*preserve-3d/u, 'Android Chromium向けに3D合成を明示する');
assert.match(androidFlipFix, /translateZ\(0\) rotateY\(180deg\)/u, 'GPU合成レイヤー上で答え側へ回転する');
assert.match(androidFlipFix, /@keyframes memory-card-android-flip-to-answer[\s\S]*rotateY\(0deg\)[\s\S]*rotateY\(180deg\)/u, 'Androidの表から裏への明示的なキーフレームを持つ');
assert.match(androidFlipFix, /@keyframes memory-card-android-flip-to-question[\s\S]*rotateY\(180deg\)[\s\S]*rotateY\(0deg\)/u, 'Androidの裏から表への明示的なキーフレームを持つ');
assert.match(androidFlipFix, /\.memory-study-card\.flip-to-answer \.memory-study-card-inner[\s\S]*memory-card-android-flip-to-answer/u, 'Android向けの前進キーフレームを反転方向クラスへ直接適用する');
assert.match(androidFlipFix, /\.memory-study-card\.flip-to-question \.memory-study-card-inner[\s\S]*memory-card-android-flip-to-question/u, 'Android向けの後退キーフレームを反転方向クラスへ直接適用する');
assert.match(androidFlipFix, /prefers-reduced-motion:\s*reduce[\s\S]*animation:\s*none !important[\s\S]*transform:\s*none !important/u, '視差低減設定のフェード切替を維持する');
assert.match(cardUx, /\.memory-simple-set-cards > \.card \+ \.card[\s\S]*margin-top:\s*0/u, '2枚目だけ下へずれるグローバルmarginを解除する');
assert.match(cardUx, /\.memory-simple-set-card[\s\S]*height:\s*100%/u, 'セットカードの高さを揃える');
assert.match(cardUx, /prefers-reduced-motion:\s*reduce/u, '視差低減設定では安全な切替へ落とす');
assert.match(compactFixes, /\.memory-card-swipe-hint[\s\S]*display:\s*none/u, '説明的なスワイプ文言を画面へ出さない');
assert.match(compactFixes, /\.memory-simple-result-grid > \.card \+ \.card[\s\S]*margin-top:\s*0/u, '結果カードが2枚目以降だけ大きくならない');
assert.match(compactFixes, /\.memory-simple-result-grid > \.card[\s\S]*min-height:\s*104px/u, '結果カードを簡潔な固定高さへ揃える');
assert.match(main, /memory-card-ux\.css[\s\S]*memory-android-flip-fix\.css[\s\S]*memory-compact-fixes\.css[\s\S]*memory-study-polish\.css/u, '問題面固定と配色補正をカードCSS群の最後へ読み込む');
assert.doesNotMatch(result, /苦手分析|Learning Target|Composition/u, '結果画面から分析導線と専門用語を削除する');
assert.match(result, /memoryReviewCardLabel\(bundle, attempt\)/u, '要復習カードは回答したSenseから利用者向けラベルを作る');
assert.match(result, /if \(!sense\) return '削除済みカード'/u, '削除済みSenseは内部IDではなく利用者向け表示へ置き換える');
assert.doesNotMatch(result, /\?\.label \?\? targetId|item\.id === attempt\?\.itemId/u, '親Itemラベルや内部IDへフォールバックしない');
assert.match(simpleSession, /!target\.exerciseId/u, '旧問題データを出題対象から除外する');
assert.match(simpleSession, /includeUnverifiedAi: false/u, '未確認AIデータを通常学習へ混ぜない');

assert.match(setup, /activeBeforeConfirm = await actionRepository\.getActiveSession\(\)/u, '開始前に最新active sessionを確認する');
assert.match(setup, /activeBeforeCreate = await actionRepository\.getActiveSession\(\)[\s\S]*activeBeforeCreate\?\.id[\s\S]*activeBeforeConfirm\?\.id/u, '確認中のactive session変更を検出する');

console.log('🎉 ALL PASS (memory simple UX contract)');
